# Generated by Django 5.0 on 2023-12-18 22:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('position', models.BooleanField(choices=[(0, 'Сотрудник'), (1, 'Директор')], default=0)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=0)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=18)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees_department.department')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='general',
            field=models.OneToOneField(limit_choices_to={'position': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='general', to='employees_department.employee'),
        ),
    ]
