# Generated by Django 5.0 on 2023-12-18 22:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='general',
            field=models.OneToOneField(limit_choices_to={'position': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='general', to='employees_department.employee', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название департамента'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=18)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees_department.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='foto',
            field=models.ImageField(upload_to='uploads/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.BooleanField(choices=[(0, 'Сотрудник'), (1, 'Директор')], default=0, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='Зарплата'),
        ),
    ]
