# Generated by Django 5.0 on 2023-12-19 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_department', '0002_alter_department_general_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='general',
            field=models.OneToOneField(limit_choices_to={'position': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general', to='employees_department.employee', verbose_name='Руководитель'),
        ),
    ]
