# Generated by Django 5.0 on 2023-12-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_department', '0003_alter_department_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='general',
            field=models.OneToOneField(limit_choices_to={'position': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general', to='employees_department.employee', verbose_name='Руководитель'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('fio', 'department')},
        ),
    ]
