# Generated by Django 5.0 on 2023-12-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_department', '0006_alter_department_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='general',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general', to='employees_department.employee', verbose_name='Руководитель'),
        ),
    ]
